services:
  - type: web
    name: indrani-paithani
    env: node
    buildCommand: npm run build
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
